config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_albert.conf:
    dst: ~/.config/albert/albert.conf
    src: config/albert/albert.conf
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - f_i3_config
    - f_compton.conf
    - f_albert.conf
    - f_xdefaults
    - f_init.vim
  vps:
    dotfiles:
    - f_zshrc
