config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_albert_config:
    dst: ~/.config/albert/albert.conf
    src: config/albert/albert.conf
  f_backlight.sh:
    dst: ~/.config/sway/backlight.sh
    src: config/sway/backlight.sh
  f_nvim_coc_config:
    dst: ~/.config/nvim/coc-settings.json
    src: config/nvim/coc-settings.json
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_nvim_config:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_sway_config:
    dst: ~/.config/sway/config
    src: config/sway/config
  f_tmux_config:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  storm:
    dotfiles:
    - f_sway_config
    - f_backlight.sh
    - f_nvim_config
    - f_nvim_coc_config
    - f_zshrc
    - f_tmux_config
    - f_albert_config
  vps:
    dotfiles:
    - f_zshrc
