actions:
  pre:
    nvim_plug_install: test -e ~/.local/share/nvim/site/autoload/plug.vim || curl
      -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    check_albert: "command -v albert >/dev/null && echo 'ERROR: albert not found'"
    check_i3: "command -v i3 >/dev/null && echo 'ERROR: i3 not found'"
    check_nvim: "command -v nvim >/dev/null && echo 'ERROR: nvim not found'"
    check_tmux: "command -v tmux >/dev/null && echo 'ERROR: tmux not found'"
    check_sway: "command -v sway >/dev/null && echo 'ERROR: sway not found'"
    check_light: "command -v light >/dev/null && echo 'ERROR: light not found'"
    check_compton: "command -v compton >/dev/null && echo 'ERROR: compton not found'"
    check_zsh: "command -v zsh >/dev/null && echo 'ERROR: zsh not found'"
    check_alacritty: "command -v alacritty >/dev/null && echo 'ERROR: alacritty not\
      \ found'"
    check_waybar: "command -v waybar >/dev/null && echo 'ERROR: waybar not found'"
  nvim_plug: nvim +PlugInstall +qall
config:
  backup: true
  create: true
  banner: false
  showdiff: true
  dotpath: dotfiles_home
dotfiles:
  f_albert_config:
    dst: ~/.config/albert/albert.conf
    src: config/albert/albert.conf
    actions:
    - check_albert
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
    actions:
    - check_compton
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
    actions:
    - check_i3
  f_sway_config:
    dst: ~/.config/sway/config
    src: config/sway/config
    actions:
    - check_sway
    - check_waybar
  d_sway_conf.d:
    src: config/sway/conf.d
    dst: ~/.config/sway/conf.d
  f_sway_backlight_sh:
    src: config/sway/backlight.sh
    dst: ~/.config/sway/backlight.sh
    actions:
    - check_sway
    - check_light
  f_tmux_config:
    dst: ~/.tmux.conf
    src: tmux.conf
    actions:
    - check_tmux
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
    actions:
    - check_zsh
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_alacritty_yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
    actions:
    - check_alacritty
  f_waybar_config:
    src: config/waybar/config
    dst: ~/.config/waybar/config
    actions:
    - check_waybar
  f_waybar_style:
    src: config/waybar/style.css
    dst: ~/.config/waybar/style.css
    actions:
    - check_waybar
  f_waybar_mediaplayer:
    src: config/waybar/mediaplayer.py
    dst: ~/.config/waybar/mediaplayer.py
    actions:
    - check_waybar
  f_nvim_config:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
    actions:
    - check_nvim
    - nvim_plug_install
    - nvim_plug
  f_nvim_plugins:
    src: config/nvim/conf.d/01-plugins.vim
    dst: ~/.config/nvim/conf.d/01-plugins.vim
  f_nvim_appearance:
    src: config/nvim/conf.d/02-appearance.vim
    dst: ~/.config/nvim/conf.d/02-appearance.vim
  f_nvim_keybinds:
    src: config/nvim/conf.d/03-keybinds.vim
    dst: ~/.config/nvim/conf.d/03-keybinds.vim
  f_nvim_languageclient:
    src: config/nvim/conf.d/04-languageclient.vim
    dst: ~/.config/nvim/conf.d/04-languageclient.vim
  f_nvim_language:
    src: config/nvim/conf.d/05-language.vim
    dst: ~/.config/nvim/conf.d/05-language.vim
  f_nvim_lightline:
    src: config/nvim/conf.d/06-lightline.vim
    dst: ~/.config/nvim/conf.d/06-lightline.vim
  f_nvim_clipboard:
    src: config/nvim/conf.d/99-clipboard.vim
    dst: ~/.config/nvim/conf.d/99-clipboard.vim
  f_nvim_syntax_vim:
    src: config/nvim/after/syntax/vim.vim
    dst: ~/.config/nvim/after/syntax/vim.vim
profiles:
  g_shell:
    dotfiles:
    - f_zshrc
    - d_zsh
  g_nvim:
    dotfiles:
    - f_nvim_config
    - f_nvim_plugins
    - f_nvim_appearance
    - f_nvim_keybinds
    - f_nvim_languageclient
    - f_nvim_language
    - f_nvim_lightline
    - f_nvim_clipboard
    - f_nvim_syntax_vim
  g_sway:
    dotfiles:
    - f_sway_config
    - d_sway_conf.d
    - f_waybar_config
    - f_waybar_style
    - f_waybar_mediaplayer
    - f_sway_backlight_sh

  storm:
    dotfiles:
    - f_tmux_config
    - f_albert_config
    - f_alacritty_yml
    include:
    - g_shell
    - g_nvim
    - g_sway

  cyclone:
    dotfiles:
    - f_tmux_config
    - f_albert_config
    - f_alacritty_yml
    include:
    - g_shell
    - g_nvim

  vps:
    dotfiles:
    - f_tmux_config
    include:
    - g_shell
    - g_nvim
