
hash nvim && alias vim=nvim

alias yayi="yay -Sl | awk '{print \$1\"/\"\$2}' | fzf -m --preview 'yay -Si {1} | grep -v \":: Querying AUR...\"'| xargs -ro yay -S"
alias yayr="yay -Qq | fzf -m --preview 'pacman -Qi {1}'| grep -v \":: Querying AUR...\" | xargs -ro yay -Rs"

alias ls=ls_extended

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias cvs="grc cvs"
alias df="grc df"
alias digg="grc digg"
alias gcc="grc gcc"
alias g++="grc g++"
alias ifconfig="grc ifconfig"
alias make="grc make"
alias mount="grc mount"
alias mtr="grc mtr"
alias netstat="grc netstat"
alias ping="grc ping"
alias ps="grc ps"
alias tail="grc tail"
alias traceroute="grc traceroute"
alias wdiff="grc wdiff"
alias blkid="grc blkid"
alias du="grc du"
alias dnf="grc dnf"
alias docker="grc docker"
alias docke-machine="grc docke-machine"
alias env="grc env"
alias id="grc id"
alias ip="grc ip"
alias iostat="grc iostat"
alias last="grc last"
alias lsattr="grc lsattr"
alias lsblk="grc lsblk"
alias lspci="grc lspci"
alias lsmod="grc lsmod"
alias lsof="grc lsof"
alias getfacl="grc getfacl"
alias getsebool="grc getsebool"
alias ulimit="grc ulimit"
alias uptime="grc uptime"
alias nmap="grc nmap"
alias fdisk="grc fdisk"
alias findmnt="grc findmnt"
alias free="grc free"
alias semanage="grc semanage"
alias sar="grc sar"
alias ss="grc ss"
alias sysctl="grc sysctl"
alias systemctl="grc systemctl"
alias stat="grc stat"
alias showmount="grc showmount"
alias tune2fs="grc tune2fs"
alias tcpdum="grc tcpdum"
