#!/bin/bash -e

while read -r line; do
    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        # if the kernel has no pkgbase, we skip it
        continue
    fi

    /usr/bin/objcopy \
        --add-section .osrel="/etc/os-release" --change-section-vma .osrel=0x20000 \
        --add-section .cmdline="/etc/cmdline" --change-section-vma .cmdline=0x30000 \
        --add-section .linux="/boot/vmlinuz-${pkgbase}" --change-section-vma .linux=0x40000 \
        --add-section .initrd="/boot/initramfs-${pkgbase}.img" --change-section-vma .initrd=0x3000000 \
        /usr/lib/systemd/boot/efi/linuxx64.efi.stub "/boot/EFI/${pkgbase}.efi"

    /usr/bin/sbctl sign -s "/boot/EFI/${pkgbase}.efi"
done
